services:
  r-lang:
    container_name: r-lang
    build: 
      context: .
      args:
        - GID=${GID:-1000}
        - UID=${UID:-1000}
    image: r-image
    tty: true
    stdin_open: true
    volumes:
      - .:/home/docker/workspace
      - renv:/home/docker/.cache/R/renv
volumes:
  renv:
    external: true
    